INSERT INTO CUSTOMER_SCHEMA.CUSTOMER(ID, NAME,DATE_CREATED) VALUES(1,'Don Collo','2022-10-12');
INSERT INTO CUSTOMER_SCHEMA.CUSTOMER(ID, NAME,DATE_CREATED) VALUES(2,'Freddi Galvan','2022-10-12');
INSERT INTO CUSTOMER_SCHEMA.PURCHASE_TRANSACTION(ID,CUSTOMER_ID,AMOUNT,TRANSACTION_DATE,PROCESS_INDICATOR) VALUES(1,1,100,'2022-10-12','N');
INSERT INTO CUSTOMER_SCHEMA.PURCHASE_TRANSACTION(ID,CUSTOMER_ID,AMOUNT,TRANSACTION_DATE,PROCESS_INDICATOR) VALUES(2,2,120,'2022-10-12','N');
INSERT INTO CUSTOMER_SCHEMA.PURCHASE_TRANSACTION(ID,CUSTOMER_ID,AMOUNT,TRANSACTION_DATE,PROCESS_INDICATOR) VALUES(3,1,200,'2022-10-12','N');