name: Use GitHub App
on:
  workflow_dispatch:
  push:
    paths:
    - .github/workflows/use-github-app.yaml

jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Get Token
      id: get_workflow_token
      uses: LexisNexis-GHA-Public/action-github-app-auth@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        base64_pem_key: ${{ secrets.APP_PRIVATE_KEY }}
        
    - name: Display Token
      id: display_token
      run: |
        echo "Token is : ${{ steps.get_workflow_token.outputs.jwt_token }}"
        
      
